### ISSUE TITLE
Consolidate notebooks with chipsalliance/silicon-notebooks

### ISSUE THREAD

**Issue by proppy** [bmurmann/Ngspice-on-Colab#1]
Hey @bmurmann, what do you think of co-maintaining those notebooks under https://github.com/chipsalliance/silicon-notebooks

@msaligane was recently asking about gf180mcu simulation notebooks, and it'd be great to make your work more discoverable (as we can also easily get them linked under https://developers.google.com/silicon/notebooks).

**Comment by bmurmann** [comment]
Sure, sounds good.

**Comment by ZeRuiCustodio** [comment]
Dear @bmurmann, I have just re-watched your presentation "Democratizing IC Design" at the SSCS Resource Center and I decided to try to run your Colab Notebooks, but none of them work. 

They fail when installing dependencies and running the following command:
!mamba env update -n base -f environment.yml
Error message:
"conda-forge/linux-64 100%[+] 5.5s
conda-forge/linux-64                              
Looking for: ['ngspice']
Your pinning does not match what's currently installed. Please remove the pin and fix your installation
  Pin: python=3.10
  Currently installed: conda-forge/linux-64::python==3.9.16=h2782a2a_0_cpython"

Do you know what has changed or who I could ask for some help?

**Comment by bmurmann** [comment]
Thanks for letting me know. I have fixed the issue, please try again.

**Comment by ZeRuiCustodio** [comment]
Dear @bmurmann, 
  I have re-run the Notebooks and everything worked as expected thank you!
  By the way in the GF180 notebook the gm and the id are swapped when creating the pandas df, resulting in the plot gm_id showing Id/gm instead.
Best regards, José
